<?php
/**
 * /api/export.php — Wellness Data Export (Phase 8)
 *
 * Allows users to download their insights, mood history, and growth milestones.
 */
require_once dirname(__DIR__) . '/includes/auth.php';
require_once dirname(__DIR__) . '/includes/db.php';
require_once dirname(__DIR__) . '/includes/functions.php';

require_active_subscription();
$user   = current_user();
$userId = (int)$user['id'];

// 1. Gather Mood History
$moods = db_query("SELECT score, label, emoji, logged_date FROM mood_logs WHERE user_id=? ORDER BY logged_date ASC", [$userId]);

// 2. Gather Insights (Memory Episodes)
$insights = db_query("SELECT summary, type, tags, session_date FROM memory_episodes WHERE user_id=? ORDER BY created_at ASC", [$userId]);

// 3. Gather Profile/Streak
$profile = db_one("SELECT purpose, tone, coach_name, day_streak FROM coach_profiles WHERE user_id=?", [$userId]);

$exportData = [
    'export_date' => date('Y-m-d H:i:s'),
    'user' => [
        'name'  => $user['name'],
        'email' => $user['email'],
        'plan'  => $user['plan']
    ],
    'wellness_profile' => $profile,
    'mood_history'     => $moods,
    'coach_insights'   => array_map(function($i) {
        $i['tags'] = json_decode($i['tags'] ?? '[]', true);
        return $i;
    }, $insights),
    'disclaimer' => "This data is generated by Solen AI based on your conversations and mood logs. It is for personal reflection and is not a clinical record."
];

header('Content-Type: application/json');
header('Content-Disposition: attachment; filename="solen_wellness_diary_' . date('Ymd') . '.json"');

echo json_encode($exportData, JSON_PRETTY_PRINT);
exit;
